package main

import (
	"time"

	"github.com/Meland-Inc/meland-client/src/client"
)

const AGENT_URL string = "agent601-dev.game.melandworld.com"

func main() {
	userToken := "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndibzYxdnUiLCJzdWIiOiJ7XCJpZFwiOlwiNzM1XCIsXCJzY2hvb2xJZFwiOlwiMFwiLFwidXNlcm5hbWVcIjpcIndibzYxdnVcIixcIm5pY2tuYW1lXCI6XCJ3OTM0ODA3N1wiLFwicmVhbG5hbWVcIjpcInc5MzQ4MDc3XCIsXCJ1c2VydHlwZVwiOlwiU1RVREVOVFwiLFwic2V4XCI6XCJNQUxFXCIsXCJlbWFpbFwiOlwiXCIsXCJtb2JpbGVcIjpcIlwiLFwiYXZhdGFyXCI6XCJodHRwczovL2JnLXByby53a2NvZGluZy5jb20vZGVmYXVsdF9hdmF0YXItMjAyMTEwMjAucG5nXCIsXCJyZWdpc3RlZEF0XCI6XCIyMDIzLTAzLTI4VDA3OjQwOjU3LjAwMFpcIixcImxhc3RMb2dpbmVkQXRcIjpcIjIwMjMtMDMtMjhUMDc6NDA6NTcuMDAwWlwiLFwibGFzdFVwZGF0ZWRBdFwiOlwiMjAyMy0wMy0yOFQwNzo0MDo1Ny4wMDBaXCIsXCJzdGF0dXNcIjoxfSIsImlhdCI6MTY4MDAwMzEyNCwiZXhwIjoxNjgwNjA3OTI0fQ.VXXOWDts4b-PJ2CJKHLal0IHosuVATL-i9jPW-oT9Zc"

	cli := client.NewGameClient(AGENT_URL, userToken)
	cli.Run()

	time.Sleep(time.Second * 10)
}
